### PR TITLE
Support for custom html options

### PR DESCRIPTION
**Pull request by jmstfv**

### CODE REVIEW

**Comment by jmstfv** [comment]
@markets are you OK with dropping Ruby 2.2 and Rails 3.2 support?

**Comment by markets** [comment]
Hi @jmstfv and thanks a lot for contributing here!

In general, would be better to send/discuss different PR for different things: 

- Travis Rubies
- Supported Rubies/Rails versions
- frozen_string_literal
- CSP support

Each topic deserves a different thread for discussion/ideas, otherwise we'll end with a messy discussion I think... Please send separate PRs for different topics :pray: 

Quick opinion about those points:

- Travis Rubies update: OK
- Supported Rubies/Rails versions: I'd like to keep current matrix, at least if we found something really hard to maintain across these versions
- frozen_string_literal: Not sure 🤔, we'd need to test this change with care (btw Matz abandoned the idea of making it default for Ruby 3 => https://bugs.ruby-lang.org/issues/11473#note-53)
- CSP support: OK

Thanks

**Comment by jmstfv** [comment]
Re: frozen strings

It has only failed on [Ruby 2.3.8 / Rails 3.2](https://travis-ci.org/markets/invisible_captcha/jobs/595720810). I've checked the error message and it seems like the problem comes from the _dummy app_, not the gem itself 🤔

I will omit that pragma from that sample app and we'll see how it goes.

And thanks for this gem, @markets . I am in the midst of a botnet attack at the moment, and it helps in keeping those ducks at bay 🙅‍♂

**Comment by markets** [comment]
I've been using this gem in 5 medium/big (2 of them with reasonable traffic) production applications with pretty good results :ok_hand:

Recently it was added to [GitLab](https://gitlab.com) too: https://gitlab.com/gitlab-org/gitlab/blob/master/Gemfile#L57

**Pull request closed without merging**
