### PR TITLE
Breakout Rails dependencies to just the essentials

### PR DESCRIPTION
**Pull request by ssunday**
I believe this does the trick. This is my first time working with `.gemspec` and appraisal. Very cool!

For https://github.com/markets/invisible_captcha/issues/93

### CODE REVIEW

**Comment by markets** [comment]
Thanks a lot @ssunday 

I just made a first quick look and it seems fine 👍🏼 , I'll take a deeper look next week. `Appraisals` is very useful for development and CI, glad you liked it!

**Comment by markets** [comment]
Hi again @ssunday 👋🏼  

After a second review and a some extra thoughts about the topic, I'm going to reject it for now sorry 🙏🏼 . Internally, we are using other Rails constants, as for example `Rails::Railtie` from `railties` gem, so this should be probably added as runtime dep... not sure :) maybe it's already required from ActiveSupport? but need to check it 🤔 

So after that, I think this change will increase maintenance costs, since we'll need to be really careful about what deps/gems need to add, and this can change by the time in different Rails versions. It's a bit less DRYer too (this can be easily fixed though). 

On the other hand, Rails core-team/community reacted fast and they shipped "official" solutions in a quite short time range. This situation (yanked gems) in Rails, fortunately 🤞🏼 , didn't happen offen, so I'll give all my trust to this community 🤗 . I'm pretty sure we all are gonna learn from that and will try to improve infrastructure to avoid future similar breakages.

Thanks a lot for sending this patch, but I'm going to close it for now. Btw, I like some of the changes of this patch, so I'm gonna port them to master (will add you as co-author).

Best,
Marc

**Comment by ssunday** [comment]
@markets Sounds good, I wish it could have been fully merged/reworked, but I get your reasoning on not wanting to maintain it. 
 
I was actually motivated to raise this PR due to maintenance cost on one of my projects that doesn't use Rails 100%. Because of this gem's rails dep, we had to do an upgrade during the mimemagic issues—without this gem, we were unaffected. It felt crazy to me that this gem was pulling in deps it was not using at all and we were not using at all, but because it was, we were forced to do a 'Rails' upgrade to be able to deploy. So this was trying to be forward thinking with reducing gem bloat and dependency problems due to this one dependency for us. Also seemed cleaner and explicit with the what the gem is actually needing... 

But! Less time for one person is more for someone else.

**Comment by markets** [comment]
I understand, this kind of situations makes one crazy! 🤯 

Another option is to use temporally your fork, that's the nice thing about the open source code 😸

**Comment by ssunday** [comment]
Yeah, that's true!

**Pull request closed without merging**
