### PR TITLE
update honeypot detection for string with only spaces

### LINKED ISSUE #66: honeypot detection failed on String with only spaces eg: " "
By looking up the source code, honeypot detection by using following codes

> if params[honeypot].present? || (params[scope] && params[scope][honeypot].present?)

if I pass " " (String with only spaces) in honeypot parameter, then spam detection will be failed.

### PR DESCRIPTION
**Pull request by bf39l**
fixes #66

### CODE REVIEW

**Comment by markets** [comment]
Hi @bf39l and thanks for trying `invisible_captcha`. To be honest, I'm not sure about this change. The idea is: the input is totally hidden for the end user, so why they added space only in the honeypot? If the honeypot is "touched", in theory we should assume this is touched by a bot/spider.

**Comment by bf39l** [comment]
Hi @markets , yes I agree with your point. Maybe I am just little bit paranoid. If bot maker fully understand the source codes, they would try to fill spaces to the inputs they detected.

**Comment by markets** [comment]
But if the bot maker fully understand the source code, they can just make the bot to ignore these honeypots... I think the current behavior is correct (and validated in several apps, more than 1.5M downloads).

I'd propose to close this one. Thanks.

**Comment by bf39l** [comment]
cool, understood. Thanks

**Pull request closed without merging**
