### PR TITLE
Submission should fails on second attempt under the timestamp_thresho…

### PR DESCRIPTION
**Pull request by markets**
…ld in the same session. So, reset the invisible_captcha_timestamp on each submission under the threshold.

More info: #24

### CODE REVIEW

**Comment by markets** [comment]
Hi @pjpoole, what do you think about this change? The timestamp will be reset each time the threshold is not reached:

- if the request is coming from a bot, throttle continues working.
- if it's coming from real users, ideally they won't hit the threshold the first time, so it won't be affected unless they reach the threshold in consequent requests => I'm not 100% sold on this to be honest

I'm planning to introduce a couple of things more in this branch (will be a new release):
- threshold customizable per action
- timestamp unique per form, so each form has a different timestamp => this will help to mitigate the problem of "stale timestamps" 

Since all this stuff related timestamps has some edge-cases, I'm also planning to introduce a third check. Now this plugin do:

```
timestamp detection => honeypot detection 
```

Will be something like:

```
bot detection by user agent => timestamp detection => honeypot detection 
```

That detection can be implemented on top of https://github.com/biola/Voight-Kampff or https://github.com/fnando/browser.

**Comment by markets** [comment]
@kikito would be nice to hear your thoughts about the changes proposed above... :)

**Comment by pjpoole** [comment]
I'll admit I don't have the exact context still loaded in my head (we managed to meet our organization's specific needs in some other manner) but from what I see and what I remember this is likely to be accurate:
> I'm not 100% sold on this to be honest

I mean, really, this is about maximum inconvenience for bot writers and minimum inconvenience for legitimate users, and a lot of users use password managers, which can fill out a login form very quickly. So it's a tricky balance to strike.

I think the "perfect" answer, given a clean mindset of several months disconnect from the problem, would be to identify the same session, and allow one quick form submission for the password manager users (no faster than, say, 0.1s), then slam the door (start using a larger timeout, resetting on every request) for subsequent requests, to handle the naive bots.

This plugin is perhaps a bit too lightweight to start generating that kind of extensive vocabulary for timeouts, so ... it's up to you.

**Comment by markets** [comment]
I'm going to close this one, I'm changing this behavior here #32.

**Pull request closed without merging**
