### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by markets** [comment]
Hi @gogainda 👋🏼 I'm not sure if TruffleRuby actually runs "complex" Rails apps. As per Travis feedback, it seems Nokogiri can't be installed. I'd like to add official support for TruffleRuby, but probably in the future (when Rails and DB adapters do it too). Currently, I don't have enough resources to keep it green, sorry.

**Comment by gogainda** [comment]
@markets actually Truffleruby it is running on complex rails applications (e.g. https://github.com/heartcombo/devise/pull/5341). The problem we see here is related to Travis and prb will not be fixed in near future. We noticed that GitHub Actions act much more stable that Travis, so if you are planing to migrate to GA we can try to run Truffleruby there

**Comment by gogainda** [comment]
btw this is the full list of supported gems https://github.com/eregon/truffleruby-gem-tracker/blob/master/gems.yml

**Comment by markets** [comment]
Yep, I have plans to move the CI to GH Actions someday, but not sure when... I still need to take a deeper look and start moving all my OSS projects (more than 10, in different langs) from Travis to GH Actions or Circle CI. Probably these platforms are kind of more flexible and powerful, but when I look at those large and complicated YAMLs... I miss the simplicity of the `.travis.yml` 👌🏼 

Thanks for the info!

**Pull request closed without merging**
