### PR TITLE
Default timestamp action redirects to root_path (Fixes #18)

### LINKED ISSUE #18: The default timestamp action doesn't cancel the form submission
Currently the default action taken when a timestamp is detected only adds an error message to the flash, and adds a message on the log. But critically, the "fast action" does not get cancelled - despite the flash message and the logged error, the form is saved unless `on_timestamp_spam` is set to something which does a `render` or a `redirect`.

I think it is odd that the default behavior is "leave the fast requests in" (and log/flash instead).

Most of the time the desirable action will be either a `render :new` or a `render :edit`, but this won't work all the time. I suggest adding a `redirect_to root_path` on the default timestamp action to prevent this. This works all the time and will shield the app against SPAM by default.

What do you think?

### PR DESCRIPTION
**Pull request by kikito**

### CODE REVIEW

**Comment by markets** [comment]
I discussed this point with @amnesia7 here: https://github.com/markets/invisible_captcha/pull/7#discussion_r53691646

What do you think about `redirect_to :back` instead  `redirect_to root_path` as the default? The referrer should be present, since we are coming from a rendered page with the form... If it's a bot, doesn't really matter, in case of false positive (human), a redirect to the previous page it's probably more apropiate.

**Comment by kikito** [comment]
`redirect_to :back` makes sense too! I will see if I can fix my PR

**Comment by kikito** [comment]
@markets I've implemented the `redirect_to :back` change in this PR.

**Comment by markets** [comment]
Thanks @kikito!

**Comment by markets** [comment]
Let me know if you need a 0.8.2 release. Are you ok to use master for now? I want to release 0.9.0 next week.

**Comment by kikito** [comment]
Hm. To be completely honest, a 0.8.2 version would help me a lot - if it's not too much to ask, please make a new release.

**Comment by markets** [comment]
@kikito you got it 😎 

https://rubygems.org/gems/invisible_captcha/versions/0.8.2

**Comment by kikito** [comment]
Thanks a lot! <3

**Pull request merged**
