### PR TITLE
Fix mime-types-data dependency for TravisCI in ruby 1.9.3

### PR DESCRIPTION
**Pull request by mltsy**
I think this should fix the ruby 1.9.3 issue on CI

### CODE REVIEW

**Comment by mltsy** [comment]
Yay! :D

**Comment by mltsy** [comment]
(You may also want to add a note to the readme that if using this with Ruby 1.9.3, you'll have to lock the mime-types gem to a version < 3 in the depending project's Gemfile or Gemfile.lock, since v3 requires ruby 2)

**Comment by markets** [comment]
Thank you a lot for this patch @mltsy 👍 

I was thinking on just drop 1.9 support... But hey, if build is passing just with this change, why not? 🚀

**Comment by mltsy** [comment]
Yay!  Yeah, I don't know how many people use 1.9 anymore (since it's reached end-of-life), but hey, as long as it still works! :smile:

**Pull request merged**
