### PR TITLE
Use redirect_back instead of redirect_to :back for Rails 5.1

### PR DESCRIPTION
**Pull request by JunichiIto**
In Rails 5.1, `redirect_to :back` is prohibited, so I changed it to use `redirect_back` instead. And I updated test codes for Rails 5.1.

Please see also http://blog.bigbinary.com/2016/02/29/rails-5-improves-redirect_to_back-with-redirect-back.html

### CODE REVIEW

**Comment by JunichiIto** [comment]
@markets Hello, any updates on this?

**Comment by markets** [comment]
Sorry for the delay @JunichiIto! I'm going to cut a new version right now with these changes.

Thanks for the PR and for `switchable_*` thing, this way we can easily support different Rails versions in CI. I'd like to keep compatibility with older versions (Ruby and Rails) while it's as easy as that.

**Comment by markets** [comment]
@JunichiIto v0.9.3 pushed to RubyGems https://rubygems.org/gems/invisible_captcha/versions/0.9.3 👍

**Comment by JunichiIto** [comment]
Thank you for the update! 🎉

**Pull request merged**
