### PR TITLE
Freeze strings

### PR DESCRIPTION
**Pull request by jmstfv**
From the previous test: https://travis-ci.org/markets/invisible_captcha/builds/595720791

I will keep adding this pragma to more files as tests pass.

### CODE REVIEW

**Comment by jmstfv** [comment]
Ruby 2.6.5 / Rails 4.2 has [failed](https://travis-ci.org/markets/invisible_captcha/builds/597297407) when I freezed gemspec strings (probably a flaky test) so I reverted that commit and re-run tests (hence no `ci skip` flag on the last commit) to make sure that nothing is broken.

**Comment by markets** [comment]
hey @jmstfv :wave: thanks again for contributing! 

As I commented in https://github.com/markets/invisible_captcha/pull/57#issuecomment-540154262, not sure about this change... It's kind of "dangerous" with no real benefit (in this case) for the final users or developers using it. I mean, in theory less strings (objects) -> less memory -> less GC pressure... but since we're not using a lot of strings in the code and the code base itself is really small, I suspect this change will have practically 0 impact in applications. 

On the other hand, having the pragma comment in only some files, IMHO introduces an overhead: now everytime we add a new file to the repo, we'll need to think about if the comment is necessary for this file or no...

In case we detect a hotspot caused by the gem, I'd be totally +1 to this, but right now it seems to me like unnecessary maintenance costs.

Thanks.

**Comment by jmstfv** [comment]
👋 @markets 

> It's kind of "dangerous"

I am really curious why you think freezing strings is a dangerous thing. Rails' itself has frozen [lots of strings](https://github.com/rails/rails/blob/master/.rubocop.yml#L129). Given that invisible_captcha depends on Rails, is there anything we should be wary of? 🤔

> I suspect this change will have practically 0 impact in applications.

Well, modern Rails apps have hundreds of gems. As much as I dislike speaking in hypotheticals, if every gem could save a couple MBs for the user, imagine the compounded benefits (cost, time, and [energy](https://superuser.com/a/40133)) for a single app multiplied by all users of those gems. We can do our part. This is free memory for no real cost.

> On the other hand, having the pragma comment in only some files, IMHO introduces an overhead

Yeah, I agree that this is a less than ideal solution, but that's because of the ancient Ruby / Rails that [failed in tests](https://travis-ci.org/markets/invisible_captcha/jobs/595720810). I think it would be safe to freeze everything after dropping support for Ruby 2.2 / Rails 3.2

My only concern would be a code that mutates strings in place, but seems like there were none of that (otherwise, tests would have failed).

Relevant article: https://www.mikeperham.com/2018/02/28/ruby-optimization-with-one-magic-comment/

**Comment by markets** [comment]
> It's kind of "dangerous"

In the sense that if there is one string mutation in some place in the code... We'll need to check it. 

> As much as I dislike speaking in hypotheticals

Yeah, I don't have these numbers neither. Actually, I work with a couple of teams using Rails, and we use really small Gemfiles in all our apps 😅 after years of development.

> We can do our part.

Agree, I'm totally +1 to improve things to make our apps consume less memory, but I usually like to measure these kind of micro-optimizations (at least to have an idea of the real impact)... There are interesting discussions about this topic in the Ruby issue tracker too: 
- https://bugs.ruby-lang.org/issues/11473
- https://bugs.ruby-lang.org/issues/16047

> My only concern would be a code that mutates strings in place, but seems like there were none of that (otherwise, tests would have failed).

ah ok! we don't have full coverage, but if all CI matrix passed, I'd say we can considere it "safe".

> Relevant article

:+1:

From the article: "reduces the generated garbage by ~100MB or ~20%!" wow such an impact for the sidekiq use case!

Do you think we can extract any kind of measure about the impact in invisible_captcha?

Btw, I think I'll merge it :) but would be amazing to have some benchmarks or real numbers in a rails app.

Thanks! Keep in touch

**Comment by jmstfv** [comment]
👋 @markets 

I have performed a very basic benchmark using [derailed benchmarks](https://github.com/schneems/derailed_benchmarks#objects-created-at-require-time) gem on the small-ish Rails 6 app. It is also possible to go more granular by pulling a gem into its own Gemfile.

Here are results for the v0.12.2:

```
allocated memory by gem
-----------------------------------
7017  invisible_captcha-0.12.2


allocated objects by gem
-----------------------------------
56  invisible_captcha-0.12.2


retained memory by gem
-----------------------------------
5984  invisible_captcha-0.12.2


retained objects by gem
-----------------------------------
32  invisible_captcha-0.12.2
```

Here are results for the [current branch](https://github.com/markets/invisible_captcha/pull/60/commits/7a0e6ad6c5e0b7ba899a07ffecfb944882bc50d5):

```
allocated memory by gem
-----------------------------------
6737  invisible_captcha-7a0e6ad6c5e0


allocated objects by gem
-----------------------------------
49  invisible_captcha-7a0e6ad6c5e0


retained memory by gem
-----------------------------------
5904  invisible_captcha-7a0e6ad6c5e0


retained objects by gem
-----------------------------------
30  invisible_captcha-7a0e6ad6c5e0
```

((7017 / 6737) - 1) * 100 ~= 4.15% improvement

There were small differences in activesupport gem as well, but I didn't include it.

**Comment by markets** [comment]
Thanks a lot @jmstfv 

Let's do it! :rocket:

**Pull request merged**
