### PR TITLE
Preparing new release

### PR DESCRIPTION
**Pull request by markets**

### CODE REVIEW

**Comment by mltsy** [comment]
I'd love to use this new release with the new time-sensitive captcha!

I see travis is failing on ruby 1.9.3 because of a conflict with the mime-types-data gem that requires ruby 2.  That's because actionmailer depends on mail, which depends on mime-types-data, and only restricts it to versions < 4.  Version 3 is the one that requires ruby 2, so you could add a dependency (maybe a development dependency?) on `'mime-types-data', '< 3'`. and that ought to fix it for ruby 1.9.3

**Comment by mltsy** [comment]
My bad, the gem you have to specify a version for is `mime-types` not `mime-types-data`.  I've submitted a PR: #9 :)

**Comment by markets** [comment]
To release a new version, I have in mind some changes more and it will be ready:

1) Allow to change threshold per action, overrides global setting (in controllers).
2) Integrate Appraisals (to test within different Rails versions: 3.2, 4.X and incoming 5.X).
3) Some docs clarifications (I want to be clear with one point: the form using invisible_captcha should probably need to deactivate the autocomplete feature).
4) Probably remove the "model style" implementation. It make sense to deal with those things at controller level, and respond (by default) with smarter responses like: head(200),... I actually don't see the need to add an error message to an object... better to focus on improve the "controller style" implementation.

What do you think about those points? cc/ @mltsy @amnesia7

**Comment by mltsy** [comment]
Those all sound like great ideas to me! :)

Depending on how soon you think that will all be ready, you could even make a minor-level release in the current state (0.8.1), and then release 0.9.0 after removing model support, updating the configuration options, and adding appraisals.

As a side note: eventually, i'd love to have some kind of field-name obfuscation too (for text inputs and textareas) to make it harder for bots to guess at valid data.  Also an IP blacklist option would be cool! (and not too much additional work probably - could even add it as a middleware)

**Comment by amnesia7** [comment]
@markets all sounds fine to me. I agree on the preference for using the controller rather than the model since if it is spam you don't really want to waste processing going from the controller through to the model for it to fail validation when really the controller could've prevented it going any further in the first place.

**Comment by kikito** [comment]
+1 to everything, especially the removal of model-based captchas (they confused me for a while).

I also like @mltsy's suggestion about releasing current master as 0.8.1 before releasing 0.9

**Comment by markets** [comment]
@kikito @mltsy @amnesia7 version 0.8.1 pushed to RubyGems: https://rubygems.org/gems/invisible_captcha/versions/0.8.1 thanks you all!

I'll use this PR to prepare 0.9 with those missing points.

**Comment by amnesia7** [comment]
@markets I'm not sure I understand the if/else in `spec/view_helpers_spec.rb` because they look the same except in a different order. 
Is there a reason for them being in a different order or have I missed something?

**Comment by markets** [comment]
@amnesia7 Yes, it's a weird change, but it also crashed in the past: https://github.com/markets/invisible_captcha/commit/314a7809e57de2077df9da6977a8065a30eb05e8

**Pull request merged**
